tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "secondary-fixed": "#e2e2e2",
                "on-tertiary-fixed-variant": "#474747",
                "secondary-fixed-dim": "#c6c6c7",
                "primary-fixed-dim": "#c9c6c5",
                "on-tertiary": "#ffffff",
                "secondary": "#5d5f5f",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#f4f0ef",
                "on-primary-fixed-variant": "#474646",
                "on-secondary-fixed": "#1a1c1c",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#c8c6c6",
                "on-tertiary-fixed": "#1b1c1c",
                "surface-container": "#f1edec",
                "tertiary": "#000000",
                "inverse-surface": "#313030",
                "outline-variant": "#c4c7c7",
                "tertiary-container": "#1b1c1c",
                "tertiary-fixed": "#e4e2e1",
                "surface-container-high": "#ebe7e6",
                "primary": "#000000",
                "surface-dim": "#ddd9d8",
                "outline": "#747878",
                "surface-tint": "#5f5e5e",
                "on-primary-fixed": "#1c1b1b",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "primary-container": "#1c1b1b",
                "surface-variant": "#e5e2e1",
                "surface-bright": "#fdf8f8",
                "on-secondary": "#ffffff",
                "on-surface": "#1c1b1b",
                "on-primary-container": "#858383",
                "surface-container-highest": "#e5e2e1",
                "primary-fixed": "#e5e2e1",
                "on-secondary-fixed-variant": "#454747",
                "on-tertiary-container": "#858383",
                "inverse-primary": "#c9c6c5",
                "surface": "#fdf8f8",
                "on-surface-variant": "#444748",
                "on-background": "#1c1b1b",
                "on-secondary-container": "#5f6161",
                "background": "#fdf8f8",
                "surface-container-low": "#f7f3f2",
                "surface-container-lowest": "#ffffff",
                "secondary-container": "#dcdddd"
            },
            "borderRadius": {
                "DEFAULT": "0",
                "lg": "0",
                "xl": "0",
                "full": "0"
            },
            "maxWidth": {
                "container-max": "1440px"
            },
            "spacing": {
                "gutter": "32px",
                "container-max": "1440px",
                "section-gap": "120px",
                "section-padding": "128px",
                "margin-mobile": "24px",
                "margin-desktop": "64px",
                "unit": "8px",
                "unit-2": "16px",
                "unit-3": "24px",
                "unit-4": "32px"
            },
            "fontFamily": {
                "caption": ["Hanken Grotesk"],
                "body-md": ["Hanken Grotesk"],
                "label-caps": ["Hanken Grotesk"],
                "label-sm": ["Hanken Grotesk"],
                "headline-md": ["Montserrat"],
                "display-xl": ["Montserrat"],
                "headline-lg": ["Montserrat"],
                "headline-lg-mobile": ["Montserrat", "sans-serif"],
                "display-xl-mobile": ["Montserrat"],
                "body-lg": ["Hanken Grotesk"]
            },
            "fontSize": {
                "caption": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "300"}],
                "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
                "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                "display-xl": ["80px", {"lineHeight": "90px", "letterSpacing": "0", "fontWeight": "700"}],
                "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "0", "fontWeight": "700"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "38px", "letterSpacing": "0", "fontWeight": "700"}],
                "display-xl-mobile": ["48px", {"lineHeight": "52px", "letterSpacing": "0", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "300"}]
            }
        },
    },
};
